[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[tool.setuptools.packages.find]
include = ["pycr*"]
exclude = ["tests*"]

[project]
name = "pycr"
version = "0.1.0"
requires-python = ">=3.9"
readme = "README.md"
dependencies = [
    "numpy>=2.0.2",
    "sympy>=1.14.0",
    "numba"
]


optional-dependencies = {  }
